version: "3.7"
networks:
  net-proxy:
    name: 'net-proxy'
    driver: 'bridge'
  net-zabbix:
    name: 'net-zabbix'
    driver: 'bridge'
    ipam:
      config:
        - subnet: '172.18.1.0/16'
          gateway: '172.18.1.1'
        

services:
  nginx-proxy:
    image: 'jwilder/nginx-proxy'
    container_name: 'nginx-proxy'
    networks:
      - 'net-proxy'
    ports:
      - '80:80'
      - '433:433'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    restart: always

  iptv-services:
    container_name: 'IPTV-Services'
    build:
      context: 'https://raw.githubusercontent.com/Losenmann/scripts/master/Docker/iptv.dockerfile'
    network_mode: 'host'
    expose:
      - '4023'
    restart: always

  homeassistant:
    container_name: 'Home-Assistant'
#   image: 'ghcr.io/home-assistant/home-assistant:stable'
    build:
      context: 'https://raw.githubusercontent.com/Losenmann/scripts/master/Docker/homeassistant.dockerfile'
    networks:
      - 'net-proxy'
    expose:
      - '8123'
    environment:
      VIRTUAL_HOST: 'site1.local'
    volumes:
#     - '/PATH_TO_YOUR_CONFIG:/config'
      - '/etc/localtime:/etc/localtime:ro'
    privileged: true
    restart: unless-stopped
