version: '3.1'
networks:
	network-zabbix:
		driver: bridge—ë

services:
	mysql:
		container_name: MariaDB
		image: mariadb:latest
		networks: network-zabbix
		ports: '3306:3306'
		restart: always
		volumes: './zabbix/mysql:/var/lib/mysql'
		environment:
			- MYSQL_ROOT_PASSWORD=YOUR-PASSWORD
			- MYSQL_DATABASE=zabbix
			- MYSQL_USER=zabbix
			- MYSQL_PASSWORD=YOUR-PASSWORD
		command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']

	zabbix-server:
		container_name: Zabbix-Server
		image: zabbix/zabbix-server-mysql:latest
		networks: network-zabbix
		ports: '10051:10051'
		volumes: './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
		environment:
			- DB_SERVER_HOST=mysql
			- MYSQL_DATABASE=zabbix
			- MYSQL_USER=zabbix
			- MYSQL_PASSWORD=YOUR-PASSWORD
		restart: always
		links: mysql
		depends_on: mysql

	zabbix-frontend:
		container_name: Zabbix-Frontend
		image: zabbix/zabbix-web-nginx-mysql:latest
		networks: network-zabbix
		ports: '8080:8080'
		environment:
			- DB_SERVER_HOST=mysql
			- MYSQL_DATABASE=zabbix
			- MYSQL_USER=zabbix
			- MYSQL_PASSWORD=YOUR-PASSWORD
			- PHP_TZ=Asia/Krasnoyarsk
			- ZBX_SERVER_NAME=RPi2
		restart: always
		links: mysql
		depends_on: mysql

	zabbix-agent:
		container_name: Zabbix-Agent
		image: zabbix/zabbix-agent2:latest
		networks: network-zabbix
		ports: '10050:10050'
		volumes: '/var/run:/var/run'
		user: root
		privileged: true
		environment:
			- ZBX_HOSTNAME=zabbix-server
			- ZBX_SERVER_HOST=zabbix-server
		restart: always
		links: zabbix-server
