networks:
    net:
        driver: bridge
            ipam:
                driver: default
                config:
                    - subnet: 172.18.0.0/29
services:
    mysql-server:
        container_name: "MariaDB"
        image: mariadb:latest
        #network_mode: bridge
        networks:
            net:
                ipv4_address: 172.18.0.3
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: "root_pwd"
            MYSQL_DATABASE: "zabbix"
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: "zabb_pwd"
        command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']
        restart: always
        healthcheck:
            #test: ["CMD-SHELL", "mysql -uroot -proot_pwd"]
            test: mysqladmin -proot_pwd ping -h localhost
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s

    zabbix-server-mysql:
        container_name: "Zabbix-Server"
        image: zabbix/zabbix-server-mysql:latest
        #network_mode: bridge
        networks:
            net:
                ipv4_address: 172.18.0.4
        ports:
            - '10051:10051'
        environment:
            DB_SERVER_HOST: mysql-server
            MYSQL_DATABASE: "zabbix"
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: "zabb_pwd"
            MYSQL_ROOT_PASSWORD: "root_pwd"
        links:
            - mysql-server
        depends_on:
            mysql-server:
                condition: service_healthy
        restart: always

    zabbix-web-nginx-mysql:
        container_name: "Zabbix-Frontend"
        image: zabbix/zabbix-web-nginx-mysql:latest
        #network_mode: bridge
        networks:
            net:
                ipv4_address: 172.18.0.5
        ports:
            - '8080:8080'
        environment:
            DB_SERVER_HOST: mysql-server
            MYSQL_DATABASE: "zabbix"
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: "zabb_pwd"
            MYSQL_ROOT_PASSWORD: "root_pwd"
            PHP_TZ: "Asia/Krasnoyarsk"
            ZBX_SERVER_NAME: "Zabbix Docker"
        links:
            - mysql-server:mysql
            - zabbix-server-mysql:zabbix-server
        depends_on:
            mysql-server:
                condition: service_healthy
        restart: always
